### PR TITLE
commands: fix tracksprocessor at old id3v2.Open() api call

### PR DESCRIPTION
**Pull request by maqiv**
commands: fix missing function parameter in tracksprocessor at id3v2 Open() call

### CODE REVIEW

**Comment by n10v** [comment]
Thank you for your contribution! I forgot about it completely.
Can you please use `Parse: false` instead of `Parse: true`? Soundcloud gives tracks anyway without any tags at all, but using `Parse: false` will (maybe?) increase the performance.

**Comment by maqiv** [comment]
fixed fix :blush:

**Comment by n10v** [comment]
Thank you! I'm very glad for new contributions, bug and feature requests!

**Comment by maqiv** [comment]
my pleasure! thanks alot for your work to the oss community!

**Pull request merged**
